key: "value"

training:
  epochs: 3
  batch_size: 8
  max_length: 512
  summary_length: 150

tokenizer:
  max_input_length: 1024
  max_target_length: 128

model:
  model_name: "t5-small"
  learning_rate: 2e-5