artifacts_root : artifacts 

data_ingestion :
  root_dir : artifacts/data_ingestion
  source_url : https://raw.githubusercontent.com/mahikshith/Fine-tuning-Transfromer-text-summarizer-using-Nvidia-Cuda/main/summarizer-data.zip
  local_data_file : artifacts/data_ingestion/data.zip 
  unzip_dir : artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  base_model: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/Trained-pegasus-model
  tokenizer_path: artifacts/model_trainer/new-tokenizer
  metric_file: artifacts/model_evaluation/metric.csv

 